spring:
  profiles:
    active: dev


---
server:
  port: 8001
# mybatis配置
mybatis:
  type-aliases-package: com.joker_yue.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring配置
spring:
  profiles: dev
  application:
    name: springcloud-config-dept   # 3个服务的名字一样
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


debug: false

# Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka # 使用集群注册
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: springcloud-provider-dept8001 # 修改默认描述信息
#    prefer-ip-address: true

# info配置
info:
  app.name: joker-springcloud-prpvider-8001
  company.name: github.com/Joker2Yue


---
server:
  port: 8001
# mybatis配置
mybatis:
  type-aliases-package: com.joker_yue.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring配置
spring:
  profiles: test
  application:
    name: springcloud-config-dept   # 3个服务的名字一样
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


debug: true

# Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka # 使用集群注册
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: springcloud-provider-dept8001 # 修改默认描述信息
#    prefer-ip-address: true

# info配置
info:
  app.name: joker-springcloud-prpvider-8001
  company.name: github.com/Joker2Yue
