server:
  port: 8003
# mybatis\u914D\u7F6E
mybatis:
  type-aliases-package: com.joker_yue.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring\u914D\u7F6E
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db03?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root


debug: false

# Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka # 使用集群注册
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka # 使用集群注册
  instance:
    instance-id: springcloud-provider-dept8003 # 修改默认描述信息
#    prefer-ip-address: true

# info配置
info:
  app.name: joker-springcloud-prpvider-8003
  company.name: github.com/Joker2Yue
