server:
  port: 7003

# Eureka配置
eureka:
  instance:
    hostname: localhost # Eureka服务端的名字（实例名称）
  client:
    register-with-eureka: false   # 是否向Eureka注册中心注册自己。由于我们现在在写服务器，不用向自己注册自己
    fetch-registry: false   # 如果为false，表示自己为注册中心
    service-url: # 监控页面
      # 集群（关联）
      defaultZone: http://eureka7001.com/eureka/,http://eureka7002.com/eureka
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
debug: true
